//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comm_App_Beta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interaction_Repo
    {
        public int User_ID { get; set; }
        public string Interact_User { get; set; }
        public System.DateTime Interaction_Date { get; set; }
        public System.DateTime Interaction_Start_Time { get; set; }
        public Nullable<System.DateTime> Interaction_Stop_Time { get; set; }
    }
}
