//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comm_App_Beta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message_Temp_Repo
    {
        public int User_ID { get; set; }
        public string Message_Text_String { get; set; }
        public Nullable<System.DateTime> Time_Stamp { get; set; }
    }
}
