//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comm_App_Beta
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Repo
    {
        public int User_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_NAme { get; set; }
        public string Communication_Key { get; set; }
        public string Active { get; set; }
        public System.DateTime Addition_Date { get; set; }
        public string User_Passord { get; set; }
        public string User_Profile_Pic { get; set; }
    }
}
